
spring :
  application:
     name: routing
  datasource:
    url : jdbc:mariadb://localhost:3307/routing-db
    username : root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

